receivers:
  otlp:
    protocols:
      grpc:

extensions:
  health_check:
  pprof:
  zpages:

exporters:
  logging:
    loglevel: debug
  honeycomb:
    api_key: "<ApiKeyHere>"
    api_url: "https://api.honeycomb.io"
    dataset: "Tests"
    debug: true

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, honeycomb]
