receivers:
  otlp:
    protocols:
      grpc:
  zipkin:
    endpoint: :9411

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  logging:
    loglevel: debug

  honeycomb:
    api_key: "<ApiKey>"
    api_url: "https://api.honeycomb.io"
    dataset: "<Dataset>"
    debug: true

  jaeger_thrift:
    url: "http://jaeger:14268/api/traces"

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
processors:
    batch:
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      exporters: [logging, honeycomb, zipkin, jaeger_thrift]
    metrics:
      receivers: [prometheus]
      exporters: [logging]
